# Generated by Django 3.2 on 2022-12-13 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_visitas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('mensaje', models.TextField(help_text='Mensaje', max_length=1000)),
                ('respondido', models.BooleanField(default=False)),
            ],
        ),
    ]
