# Generated by Django 3.2 on 2022-12-12 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_visitas'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='editado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comentario',
            name='modificado',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
