# Generated by Django 3.2 on 2022-12-13 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20221212_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={},
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
