# Generated by Django 3.2 on 2022-12-14 02:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('noticias', '0004_auto_20221213_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_comentarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noticia',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_noticias', to=settings.AUTH_USER_MODEL),
        ),
    ]
