# Generated by Django 3.2 on 2022-12-18 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_contacto'),
        ('noticias', '0004_auto_20221213_0044'),
    ]

    operations = [
    ]
