# Generated by Django 3.2 on 2022-12-19 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0005_auto_20221213_2343'),
        ('noticias', '0005_merge_0003_contacto_0004_auto_20221213_0044'),
    ]

    operations = [
    ]
